matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r requirements.txt
    - language: node_js
      node_js:
        - "iojs"
        - "8"
      install:
        - npm install
        - grunt dist
